// import { Mistral } from '@mistralai/mistralai';

// const apiKey = import.meta.env.VITE_MISTRAL_API_KEY;
// const useMockAI = !apiKey;
// const client = apiKey ? new Mistral({ apiKey }) : null;

// export class TheoryQuestionGenerator {
//   static async generateQuestions(content: string, subject: string, topic: string) {
//     if (useMockAI) {
//       await new Promise(resolve => setTimeout(resolve, 2500));
      
//       // Generate sophisticated mock questions based on content analysis
//       const contentLines = content.split('\n').filter(line => line.trim().length > 20);
//       const keyTerms = content.toLowerCase().match(/\b[a-z]{4,}\b/g)?.slice(0, 15) || [];
//       const hasFormulas = /[=+\-*/()0-9]/.test(content) || /\$.*\$/.test(content);
//       const hasDefinitions = /definition|concept|principle|theory|law|formula/i.test(content);
//       const hasExamples = /example|instance|case|illustration|application/i.test(content);
//       const hasSteps = /step|process|method|procedure|algorithm/i.test(content);
//       const sentences = content.split(/[.!?]+/).filter(s => s.trim().length > 30).slice(0, 15);
      
//       // Extract key concepts for sophisticated questions
//       const concepts = content.match(/(?:concept|principle|theory|law|rule|property|characteristic|feature|aspect|element|component|factor|criterion|condition|requirement|assumption|hypothesis|conclusion|implication|consequence|result|effect|cause|reason|purpose|objective|goal|aim|function|role|significance|importance|relevance|application|use|utility|benefit|advantage|limitation|disadvantage|challenge|problem|issue|difficulty|complexity|relationship|connection|correlation|association|interaction|influence|impact|dependency|interdependence)s?\s+(?:of|in|for|with|between|among|regarding|concerning|related to|associated with|connected to|linked to|tied to|bound to|dependent on|influenced by|affected by|determined by|characterized by|defined by|described by|explained by|illustrated by|demonstrated by|shown by|indicated by|suggested by|implied by|inferred from|derived from|based on|founded on|grounded in|rooted in|stemming from|arising from|emerging from|resulting from|leading to|contributing to|giving rise to|bringing about|causing|producing|generating|creating|forming|establishing|developing|building|constructing|designing|planning|organizing|structuring|arranging|configuring|setting up|implementing|executing|performing|carrying out|conducting|undertaking|pursuing|following|adopting|applying|utilizing|employing|using|leveraging|exploiting|harnessing|capitalizing on|taking advantage of|making use of|drawing on|relying on|depending on|counting on|banking on|trusting in|believing in|having faith in|being confident in|being certain of|being sure of|being convinced of|being persuaded of|being satisfied with|being pleased with|being happy with|being content with|being comfortable with|being familiar with|being acquainted with|being aware of|being conscious of|being mindful of|being attentive to|being alert to|being sensitive to|being responsive to|being receptive to|being open to|being willing to|being ready to|being prepared to|being able to|being capable of|being competent in|being skilled in|being proficient in|being expert in|being knowledgeable about|being informed about|being educated about|being trained in|being experienced in|being practiced in|being versed in|being well-versed in|being conversant with|being fluent in|being articulate about|being eloquent about|being expressive about|being communicative about|being informative about|being instructive about|being educational about|being enlightening about|being illuminating about|being revealing about|being disclosing about|being exposing about|being uncovering about|being discovering about|being finding about|being identifying about|being recognizing about|being acknowledging about|being admitting about|being confessing about|being declaring about|being stating about|being asserting about|being claiming about|being maintaining about|being insisting about|being emphasizing about|being stressing about|being highlighting about|being underscoring about|being accentuating about|being focusing on|being concentrating on|being centering on|being revolving around|being based on|being founded on|being grounded in|being rooted in|being anchored in|being established in|being situated in|being located in|being positioned in|being placed in|being set in|being embedded in|being integrated into|being incorporated into|being included in|being contained in|being comprised of|being composed of|being made up of|being consisting of|being formed by|being created by|being produced by|being generated by|being developed by|being built by|being constructed by|being designed by|being planned by|being organized by|being structured by|being arranged by|being configured by|being set up by|being implemented by|being executed by|being performed by|being carried out by|being conducted by|being undertaken by|being pursued by|being followed by|being adopted by|being applied by|being utilized by|being employed by|being used by|being leveraged by|being exploited by|being harnessed by|being capitalized on by|being taken advantage of by|being made use of by|being drawn on by|being relied on by|being depended on by|being counted on by|being banked on by|being trusted in by|being believed in by|being had faith in by|being confident in by|being certain of by|being sure of by|being convinced of by|being persuaded of by|being satisfied with by|being pleased with by|being happy with by|being content with by|being comfortable with by|being familiar with by|being acquainted with by|being aware of by|being conscious of by|being mindful of by|being attentive to by|being alert to by|being sensitive to by|being responsive to by|being receptive to by|being open to by|being willing to by|being ready to by|being prepared to by|being able to by|being capable of by|being competent in by|being skilled in by|being proficient in by|being expert in by|being knowledgeable about by|being informed about by|being educated about by|being trained in by|being experienced in by|being practiced in by|being versed in by|being well-versed in by|being conversant with by|being fluent in by)\s+[\w\s]+/gi) || [];
      
//       return JSON.stringify({
//         questions: [
//           {
//             id: '1',
//             question: hasDefinitions ? 
//               `Analyze the relationship between the key concepts presented in the theory. Which statement best demonstrates the interconnection between the primary principles discussed?` :
//               `Based on your understanding of the theoretical framework presented, which conclusion can be drawn about the underlying mechanisms?`,
//             options: [
//               sentences[0]?.substring(0, 80) + '...' || 'The concepts are fundamentally interconnected through shared principles',
//               sentences[1]?.substring(0, 80) + '...' || 'Each concept operates independently without significant overlap',
//               'The relationships are purely theoretical with no practical implications',
//               'The concepts contradict each other in fundamental ways'
//             ],
//             correctAnswer: 0,
//             explanation: `This demonstrates deep understanding of how the theoretical concepts work together as presented in the content.`,
//             topic: `${topic} - Conceptual Analysis`,
//             difficulty: 'hard',
//             questionType: 'analysis'
//           },
//           {
//             id: '2',
//             question: hasFormulas ? 
//               `Evaluate the mathematical relationships presented. If the given conditions were modified, what would be the most significant impact on the overall framework?` :
//               `Critically assess the theoretical approach described. What would be the primary limitation of applying this approach in complex scenarios?`,
//             options: [
//               hasFormulas ? 'The mathematical relationships would require complete recalibration' : 'The theoretical limitations would become more pronounced',
//               hasFormulas ? 'Only minor adjustments to coefficients would be needed' : 'The approach would remain equally effective',
//               hasFormulas ? 'The formulas would become invalid entirely' : 'No significant limitations would emerge',
//               hasFormulas ? 'The relationships would reverse completely' : 'The approach would become more robust'
//             ],
//             correctAnswer: 0,
//             explanation: `This requires critical evaluation of the theoretical framework and understanding of its limitations and dependencies.`,
//             topic: `${topic} - Critical Evaluation`,
//             difficulty: 'hard',
//             questionType: 'evaluation'
//           },
//           {
//             id: '3',
//             question: hasExamples ? 
//               `Synthesize the examples provided with the theoretical principles. How would you apply this integrated understanding to solve a novel problem in this domain?` :
//               `Given the theoretical foundation presented, how would you design an approach to address a complex, multi-faceted problem in this area?`,
//             options: [
//               hasExamples ? 'Combine the example methodologies with theoretical principles for a comprehensive solution' : 'Apply the theoretical framework systematically while adapting to specific constraints',
//               hasExamples ? 'Use only the examples without considering theoretical implications' : 'Rely solely on theoretical principles without practical considerations',
//               hasExamples ? 'Modify the examples to fit the theory exactly' : 'Ignore theoretical constraints and focus on practical solutions',
//               hasExamples ? 'Treat examples and theory as completely separate approaches' : 'Use trial and error without theoretical guidance'
//             ],
//             correctAnswer: 0,
//             explanation: `This demonstrates the ability to synthesize theoretical knowledge with practical applications for problem-solving.`,
//             topic: `${topic} - Application & Synthesis`,
//             difficulty: 'hard',
//             questionType: 'synthesis'
//           },
//           {
//             id: '4',
//             question: keyTerms.length > 2 ? 
//               `Compare and contrast the roles of "${keyTerms[0]}" and "${keyTerms[1]}" in the theoretical framework. What is the most significant difference in their functional contributions?` :
//               `Analyze the hierarchical structure of concepts presented. Which element serves as the foundational basis for the entire theoretical framework?`,
//             options: [
//               keyTerms.length > 2 ? `${keyTerms[0]} provides structural foundation while ${keyTerms[1]} enables dynamic functionality` : 'The foundational element establishes the theoretical basis for all subsequent concepts',
//               keyTerms.length > 2 ? `${keyTerms[0]} and ${keyTerms[1]} serve identical functions in different contexts` : 'All elements contribute equally without hierarchical structure',
//               keyTerms.length > 2 ? `${keyTerms[1]} is more fundamental than ${keyTerms[0]} in all applications` : 'The most complex element serves as the foundation',
//               keyTerms.length > 2 ? `Both terms represent the same concept with different terminology` : 'No single element is more foundational than others'
//             ],
//             correctAnswer: 0,
//             explanation: `This requires comparative analysis and understanding of the functional roles of different elements within the theoretical system.`,
//             topic: `${topic} - Comparative Analysis`,
//             difficulty: 'medium',
//             questionType: 'comparison'
//           },
//           {
//             id: '5',
//             question: hasSteps ? 
//               `Evaluate the procedural sequence described. If step 3 were to be modified significantly, what would be the cascading effects on the subsequent steps?` :
//               `Assess the logical progression of ideas presented. Which transition point represents the most critical juncture in the theoretical development?`,
//             options: [
//               hasSteps ? 'Steps 4-6 would require fundamental restructuring to maintain logical consistency' : 'The transition from basic principles to advanced applications represents the critical juncture',
//               hasSteps ? 'Only step 4 would need minor adjustments' : 'All transition points are equally important',
//               hasSteps ? 'No other steps would be affected' : 'The initial introduction is the most critical point',
//               hasSteps ? 'The entire sequence would need to be reversed' : 'The conclusion represents the most critical transition'
//             ],
//             correctAnswer: 0,
//             explanation: `This tests understanding of logical dependencies and the ability to predict consequences of changes within a system.`,
//             topic: `${topic} - Systems Thinking`,
//             difficulty: 'medium',
//             questionType: 'consequence-analysis'
//           },
//           {
//             id: '6',
//             question: `Integrate your understanding of this ${topic} content with broader ${subject} principles. Which statement best represents how this specific topic contributes to the overall discipline?`,
//             options: [
//               `This topic provides essential building blocks that enable understanding of advanced ${subject} concepts`,
//               `This topic is an isolated area with minimal connection to other ${subject} areas`,
//               `This topic contradicts fundamental ${subject} principles`,
//               `This topic is purely theoretical with no practical ${subject} applications`
//             ],
//             correctAnswer: 0,
//             explanation: `This requires integration of specific topic knowledge with broader disciplinary understanding, demonstrating comprehensive learning.`,
//             topic: `${topic} - Disciplinary Integration`,
//             difficulty: 'medium',
//             questionType: 'integration'
//           },
//           {
//             id: '7',
//             question: `Predict the implications if the core assumptions underlying this ${topic} theory were proven incorrect. What would be the most likely outcome for the field of ${subject}?`,
//             options: [
//               `Fundamental revision of related theories and methodologies would be necessary`,
//               `No significant changes would be required in the field`,
//               `Only minor adjustments to terminology would be needed`,
//               `The entire field of ${subject} would become obsolete`
//             ],
//             correctAnswer: 0,
//             explanation: `This tests the ability to understand theoretical foundations and predict broader implications of fundamental changes.`,
//             topic: `${topic} - Theoretical Implications`,
//             difficulty: 'hard',
//             questionType: 'prediction'
//           },
//           {
//             id: '8',
//             question: `Design a research approach to validate the key claims made in this ${topic} content. What would be the most robust methodology?`,
//             options: [
//               `Combine empirical testing with theoretical modeling to validate both practical and conceptual aspects`,
//               `Use only theoretical analysis without empirical validation`,
//               `Rely solely on expert opinions and consensus`,
//               `Apply the methodology exactly as described without modification`
//             ],
//             correctAnswer: 0,
//             explanation: `This requires understanding of research methodology and the ability to design validation approaches for theoretical content.`,
//             topic: `${topic} - Research Design`,
//             difficulty: 'hard',
//             questionType: 'methodology'
//           }
//         ]
//       });
//     }

//     const prompt = this.getTheoryQuizPrompt(content, subject, topic);

//     try {
//       const response = await client!.chat.complete({
//         model: 'mistral-large-latest',
//         messages: [{ role: 'user', content: prompt }],
//         temperature: 0.4, // Balanced for creativity while maintaining accuracy
//         max_tokens: 6000,
//       });

//       return response.choices[0]?.message?.content || this.getFallbackQuestions(subject, topic);
//     } catch (error) {
//       console.error('Error generating theory quiz questions:', error);
//       return this.getFallbackQuestions(subject, topic);
//     }
//   }

//   private static getTheoryQuizPrompt(content: string, subject: string, topic: string): string {
//     const truncatedContent = content.length > 8000 ? content.substring(0, 8000) + '...' : content;

//     return `You are an expert examination specialist and cognitive assessment designer with 25+ years of experience creating high-level competitive exam questions for ${subject}. Your expertise lies in crafting questions that test deep understanding, critical thinking, and application skills rather than mere memorization.

// MISSION: Create 8-12 sophisticated, medium-to-hard difficulty multiple-choice questions based EXCLUSIVELY on the provided theory content for "${topic}" in ${subject}.

// THEORY CONTENT TO ANALYZE:
// ${truncatedContent}

// CRITICAL QUALITY STANDARDS:

// 1. **DIFFICULTY LEVEL**: MEDIUM TO HARD ONLY
//    - NO basic recall or definition questions
//    - Focus on analysis, synthesis, evaluation, and application
//    - Require multi-step reasoning and concept integration
//    - Test understanding of relationships, implications, and consequences

// 2. **COGNITIVE COMPLEXITY REQUIREMENTS**:
//    - **Analysis**: Break down complex concepts, identify relationships, compare/contrast elements
//    - **Synthesis**: Combine multiple concepts, integrate ideas, create new understanding
//    - **Evaluation**: Judge validity, assess effectiveness, critique approaches, predict outcomes
//    - **Application**: Apply concepts to new situations, solve complex problems, design solutions

// 3. **QUESTION SOPHISTICATION**:
//    - Each question should require 30-60 seconds of thoughtful consideration
//    - Avoid questions answerable through simple keyword matching
//    - Create scenarios that test conceptual understanding
//    - Include questions that require inference and logical reasoning

// 4. **CONTENT FIDELITY**:
//    - Extract ONLY from the provided theory content
//    - Use specific terminology, examples, and concepts from the text
//    - Maintain scientific/academic accuracy
//    - Reference specific details, relationships, or examples mentioned

// 5. **DISTRACTOR QUALITY** (Incorrect Options):
//    - Create plausible but incorrect options that test common misconceptions
//    - Include options that are partially correct but incomplete
//    - Design distractors that require careful analysis to eliminate
//    - Avoid obviously wrong or nonsensical options

// QUESTION TYPES TO PRIORITIZE:

// **ANALYSIS QUESTIONS** (30%):
// - "Analyze the relationship between X and Y. What is the most significant factor that..."
// - "Compare the effectiveness of approaches A and B. Which statement best explains..."
// - "Examine the underlying assumptions. Which assumption is most critical for..."

// **SYNTHESIS QUESTIONS** (25%):
// - "Integrate concepts X, Y, and Z. How would you design a solution that..."
// - "Combine the principles discussed. What would be the optimal approach to..."
// - "Synthesize the information presented. Which strategy would most effectively..."

// **EVALUATION QUESTIONS** (25%):
// - "Evaluate the validity of the claim that... Which evidence best supports..."
// - "Assess the limitations of the approach described. What is the primary weakness..."
// - "Judge the effectiveness of the methodology. Under what conditions would it fail..."

// **APPLICATION QUESTIONS** (20%):
// - "Apply the principles to a new scenario where... What would be the expected outcome..."
// - "Given the constraints described, how would you modify the approach to..."
// - "Using the framework presented, solve the following complex problem..."

// ADVANCED QUESTION STRUCTURES:

// 1. **Scenario-Based Questions**: Present a complex situation and ask for analysis/solution
// 2. **Cause-Effect Questions**: Test understanding of relationships and consequences
// 3. **Comparative Questions**: Require evaluation of multiple approaches/concepts
// 4. **Predictive Questions**: Ask students to predict outcomes based on principles
// 5. **Design Questions**: Require students to create solutions using learned concepts
// 6. **Troubleshooting Questions**: Present problems and ask for diagnostic analysis

// JSON RESPONSE FORMAT:
// {
//   "questions": [
//     {
//       "id": "unique_id",
//       "question": "Sophisticated question requiring deep analysis of content",
//       "options": ["Correct answer demonstrating deep understanding", "Plausible but incorrect option", "Another sophisticated distractor", "Complex but wrong alternative"],
//       "correctAnswer": 0,
//       "explanation": "Detailed explanation connecting answer to specific content elements and demonstrating why other options are incorrect",
//       "topic": "${topic} - Specific Aspect",
//       "difficulty": "medium|hard",
//       "questionType": "analysis|synthesis|evaluation|application"
//     }
//   ]
// }

// QUALITY ASSURANCE CHECKLIST:
// ✓ Each question tests understanding beyond memorization
// ✓ Questions require 30+ seconds of thoughtful analysis
// ✓ All options are plausible and require careful consideration
// ✓ Explanations connect to specific content elements
// ✓ Questions progress from medium to hard difficulty
// ✓ Content fidelity is maintained throughout
// ✓ Academic language and terminology are used appropriately
// ✓ Questions would challenge even well-prepared students

// FORBIDDEN ELEMENTS:
// ✗ Simple definition questions ("What is X?")
// ✗ Direct fact recall ("According to the text, X equals...")
// ✗ Obvious or silly distractors
// ✗ Questions answerable without reading the content
// ✗ Ambiguous or poorly worded questions
// ✗ Questions with multiple correct answers
// ✗ Content not present in the provided material

// Generate questions that would make a professor proud - sophisticated, challenging, and truly testing deep understanding of ${topic} in ${subject}.`;
//   }

//   private static getFallbackQuestions(subject: string, topic: string): string {
//     return JSON.stringify({
//       questions: [
//         {
//           id: '1',
//           question: `Analyze the fundamental principles underlying ${topic} in ${subject}. Which factor most significantly influences the overall theoretical framework?`,
//           options: [
//             'The interconnected nature of core concepts and their dependencies',
//             'The chronological order in which concepts were discovered',
//             'The complexity of mathematical representations',
//             'The number of practical applications available'
//           ],
//           correctAnswer: 0,
//           explanation: `Understanding the interconnected nature of concepts is crucial for mastering ${topic} in ${subject}.`,
//           topic: `${topic} - Fundamental Analysis`,
//           difficulty: 'medium',
//           questionType: 'analysis'
//         },
//         {
//           id: '2',
//           question: `Evaluate the implications of applying ${topic} principles to solve complex problems. What would be the most critical consideration?`,
//           options: [
//             'Understanding the boundary conditions and limitations of the theoretical framework',
//             'Memorizing all formulas and definitions perfectly',
//             'Following procedures exactly as written',
//             'Using the most complex approach available'
//           ],
//           correctAnswer: 0,
//           explanation: `Critical evaluation requires understanding limitations and boundary conditions of theoretical applications.`,
//           topic: `${topic} - Critical Evaluation`,
//           difficulty: 'hard',
//           questionType: 'evaluation'
//         }
//       ]
//     });
//   }
// }






import { Mistral } from '@mistralai/mistralai';

const apiKey = import.meta.env.VITE_MISTRAL_API_KEY;
const useMockAI = !apiKey;
const client = apiKey ? new Mistral({ apiKey }) : null;

export class TheoryQuestionGenerator {
  static async generateQuestions(content: string, subject: string, topic: string, examLevel: string) { // Added examLevel parameter
    if (useMockAI) {
      await new Promise(resolve => setTimeout(resolve, 2500));
      
      // Generate sophisticated mock questions based on content analysis
      const contentLines = content.split('\n').filter(line => line.trim().length > 20);
      const keyTerms = content.toLowerCase().match(/\b[a-z]{4,}\b/g)?.slice(0, 15) || [];
      const hasFormulas = /[=+\-*/()0-9]/.test(content) || /\$.*\$/.test(content);
      const hasDefinitions = /definition|concept|principle|theory|law|formula/i.test(content);
      const hasExamples = /example|instance|case|illustration|application/i.test(content);
      const hasSteps = /step|process|method|procedure|algorithm/i.test(content);
      const sentences = content.split(/[.!?]+/).filter(s => s.trim().length > 30).slice(0, 15);
      
      // Extract key concepts for sophisticated questions
      const concepts = content.match(/(?:concept|principle|theory|law|rule|property|characteristic|feature|aspect|element|component|factor|criterion|condition|requirement|assumption|hypothesis|conclusion|implication|consequence|result|effect|cause|reason|purpose|objective|goal|aim|function|role|significance|importance|relevance|application|use|utility|benefit|advantage|limitation|disadvantage|challenge|problem|issue|difficulty|complexity|relationship|connection|correlation|association|interaction|influence|impact|dependency|interdependence)s?\s+(?:of|in|for|with|between|among|regarding|concerning|related to|associated with|connected to|linked to|tied to|bound to|dependent on|influenced by|affected by|determined by|characterized by|defined by|described by|explained by|illustrated by|demonstrated by|shown by|indicated by|suggested by|implied by|inferred from|derived from|based on|founded on|grounded in|rooted in|stemming from|arising from|emerging from|resulting from|leading to|contributing to|giving rise to|bringing about|causing|producing|generating|creating|forming|establishing|developing|building|constructing|designing|planning|organizing|structuring|arranging|configuring|setting up|implementing|executing|performing|carrying out|conducting|undertaking|pursuing|following|adopting|applying|utilizing|employing|using|leveraging|exploiting|harnessing|capitalizing on|taking advantage of|making use of|drawing on|relying on|depending on|counting on|banking on|trusting in|believing in|having faith in|being confident in|being certain of|being sure of|being convinced of|being persuaded of|being satisfied with|being pleased with|being happy with|being content with|being comfortable with|being familiar with|being acquainted with|being aware of|being conscious of|being mindful of|being attentive to|being alert to|being sensitive to|being responsive to|being receptive to|being open to|being willing to|being ready to|being prepared to|being able to|being capable of|being competent in|being skilled in|being proficient in|being expert in|being knowledgeable about|being informed about|being educated about|being trained in|being experienced in|being practiced in|being versed in|being well-versed in|being conversant with|being fluent in|being articulate about|being eloquent about|being expressive about|being communicative about|being informative about|being instructive about|being educational about|being enlightening about|being illuminating about|being revealing about|being disclosing about|being exposing about|being uncovering about|being discovering about|being finding about|being identifying about|being recognizing about|being acknowledging about|being admitting about|being confessing about|being declaring about|being stating about|being asserting about|being claiming about|being maintaining about|being insisting about|being emphasizing about|being stressing about|being highlighting about|being underscoring about|being accentuating about|being focusing on|being concentrating on|being centering on|being revolving around|being based on|being founded on|being grounded in|being rooted in|being anchored in|being established in|being situated in|being located in|being positioned in|being placed in|being set in|being embedded in|being integrated into|being incorporated into|being included in|being contained in|being comprised of|being composed of|being made up of|being consisting of|being formed by|being created by|being produced by|being generated by|being developed by|being built by|being constructed by|being designed by|being planned by|being organized by|being structured by|being arranged by|being configured by|being set up by|being implemented by|being executed by|being performed by|being carried out by|being conducted by|being undertaken by|being pursued by|being followed by|being adopted by|being applied by|being utilized by|being employed by|being used by|being leveraged by|being exploited by|being harnessed by|being capitalized on by|being taken advantage of by|being made use of by|being drawn on by|being relied on by|being depended on by|being counted on by|being banked on by|being trusted in by|being believed in by|being had faith in by|being confident in by|being certain of by|being sure of by|being convinced of by|being persuaded of by|being satisfied with by|being pleased with by|being happy with by|being content with by|being comfortable with by|being familiar with by|being acquainted with by|being aware of by|being conscious of by|being mindful of by|being attentive to by|being alert to by|being sensitive to by|being responsive to by|being receptive to by|being open to by|being willing to by|being ready to by|being prepared to by|being able to by|being capable of by|being competent in by|being skilled in by|being proficient in by|being expert in by|being knowledgeable about by|being informed about by|being educated about by|being trained in by|being experienced in by|being practiced in by|being versed in by|being well-versed in by|being conversant with by|being fluent in by)\s+[\w\s]+/gi) || [];
      
      return JSON.stringify({
        questions: [
          {
            id: '1',
            question: hasDefinitions ? 
              `Analyze the relationship between the key concepts presented in the theory. Which statement best demonstrates the interconnection between the primary principles discussed?` :
              `Based on your understanding of the theoretical framework presented, which conclusion can be drawn about the underlying mechanisms?`,
            options: [
              sentences[0]?.substring(0, 80) + '...' || 'The concepts are fundamentally interconnected through shared principles',
              sentences[1]?.substring(0, 80) + '...' || 'Each concept operates independently without significant overlap',
              'The relationships are purely theoretical with no practical implications',
              'The concepts contradict each other in fundamental ways'
            ],
            correctAnswer: 0,
            explanation: `This demonstrates deep understanding of how the theoretical concepts work together as presented in the content, relevant for ${examLevel} exams.`,
            topic: `${topic} - Conceptual Analysis`,
            difficulty: 'hard',
            questionType: 'analysis'
          },
          {
            id: '2',
            question: hasFormulas ? 
              `Evaluate the mathematical relationships presented. If the given conditions were modified, what would be the most significant impact on the overall framework?` :
              `Critically assess the theoretical approach described. What would be the primary limitation of applying this approach in complex scenarios?`,
            options: [
              hasFormulas ? 'The mathematical relationships would require complete recalibration' : 'The theoretical limitations would become more pronounced',
              hasFormulas ? 'Only minor adjustments to coefficients would be needed' : 'The approach would remain equally effective',
              hasFormulas ? 'The formulas would become invalid entirely' : 'No significant limitations would emerge',
              hasFormulas ? 'The relationships would reverse completely' : 'The approach would become more robust'
            ],
            correctAnswer: 0,
            explanation: `This requires critical evaluation of the theoretical framework and understanding of its limitations and dependencies, as expected for ${examLevel} level.`,
            topic: `${topic} - Critical Evaluation`,
            difficulty: 'hard',
            questionType: 'evaluation'
          },
          {
            id: '3',
            question: hasExamples ? 
              `Synthesize the examples provided with the theoretical principles. How would you apply this integrated understanding to solve a novel problem in this domain?` :
              `Given the theoretical foundation presented, how would you design an approach to address a complex, multi-faceted problem in this area?`,
            options: [
              hasExamples ? 'Combine the example methodologies with theoretical principles for a comprehensive solution' : 'Apply the theoretical framework systematically while adapting to specific constraints',
              hasExamples ? 'Use only the examples without considering theoretical implications' : 'Rely solely on theoretical principles without practical considerations',
              hasExamples ? 'Modify the examples to fit the theory exactly' : 'Ignore theoretical constraints and focus on practical solutions',
              hasExamples ? 'Treat examples and theory as completely separate approaches' : 'Use trial and error without theoretical guidance'
            ],
            correctAnswer: 0,
            explanation: `This demonstrates the ability to synthesize theoretical knowledge with practical applications for problem-solving, crucial for ${examLevel} exams.`,
            topic: `${topic} - Application & Synthesis`,
            difficulty: 'hard',
            questionType: 'synthesis'
          },
          {
            id: '4',
            question: keyTerms.length > 2 ? 
              `Compare and contrast the roles of "${keyTerms[0]}" and "${keyTerms[1]}" in the theoretical framework. What is the most significant difference in their functional contributions?` :
              `Analyze the hierarchical structure of concepts presented. Which element serves as the foundational basis for the entire theoretical framework?`,
            options: [
              keyTerms.length > 2 ? `${keyTerms[0]} provides structural foundation while ${keyTerms[1]} enables dynamic functionality` : 'The foundational element establishes the theoretical basis for all subsequent concepts',
              keyTerms.length > 2 ? `${keyTerms[0]} and ${keyTerms[1]} serve identical functions in different contexts` : 'All elements contribute equally without hierarchical structure',
              keyTerms.length > 2 ? `${keyTerms[1]} is more fundamental than ${keyTerms[0]} in all applications` : 'The most complex element serves as the foundation',
              keyTerms.length > 2 ? `Both terms represent the same concept with different terminology` : 'No single element is more foundational than others'
            ],
            correctAnswer: 0,
            explanation: `This requires comparative analysis and understanding of the functional roles of different elements within the theoretical system, relevant for ${examLevel} level.`,
            topic: `${topic} - Comparative Analysis`,
            difficulty: 'medium',
            questionType: 'comparison'
          },
          {
            id: '5',
            question: hasSteps ? 
              `Evaluate the procedural sequence described. If step 3 were to be modified significantly, what would be the cascading effects on the subsequent steps?` :
              `Assess the logical progression of ideas presented. Which transition point represents the most critical juncture in the theoretical development?`,
            options: [
              hasSteps ? 'Steps 4-6 would require fundamental restructuring to maintain logical consistency' : 'The transition from basic principles to advanced applications represents the critical juncture',
              hasSteps ? 'Only step 4 would need minor adjustments' : 'All transition points are equally important',
              hasSteps ? 'No other steps would be affected' : 'The initial introduction is the most critical point',
              hasSteps ? 'The entire sequence would need to be reversed' : 'The conclusion represents the most critical transition'
            ],
            correctAnswer: 0,
            explanation: `This tests understanding of logical dependencies and the ability to predict consequences of changes within a system, as expected for ${examLevel} level.`,
            topic: `${topic} - Systems Thinking`,
            difficulty: 'medium',
            questionType: 'consequence-analysis'
          },
          {
            id: '6',
            question: `Integrate your understanding of this ${topic} content with broader ${subject} principles. Which statement best represents how this specific topic contributes to the overall discipline?`,
            options: [
              `This topic provides essential building blocks that enable understanding of advanced ${subject} concepts`,
              `This topic is an isolated area with minimal connection to other ${subject} areas`,
              `This topic contradicts fundamental ${subject} principles`,
              `This topic is purely theoretical with no practical ${subject} applications`
            ],
            correctAnswer: 0,
            explanation: `This requires integration of specific topic knowledge with broader disciplinary understanding, demonstrating comprehensive learning for ${examLevel} exams.`,
            topic: `${topic} - Disciplinary Integration`,
            difficulty: 'medium',
            questionType: 'integration'
          },
          {
            id: '7',
            question: `Predict the implications if the core assumptions underlying this ${topic} theory were proven incorrect. What would be the most likely outcome for the field of ${subject}?`,
            options: [
              `Fundamental revision of related theories and methodologies would be necessary`,
              `No significant changes would be required in the field`,
              `Only minor adjustments to terminology would be needed`,
              `The entire field of ${subject} would become obsolete`
            ],
            correctAnswer: 0,
            explanation: `This tests the ability to understand theoretical foundations and predict broader implications of fundamental changes, crucial for ${examLevel} level.`,
            topic: `${topic} - Theoretical Implications`,
            difficulty: 'hard',
            questionType: 'prediction'
          },
          {
            id: '8',
            question: `Design a research approach to validate the key claims made in this ${topic} content. What would be the most robust methodology?`,
            options: [
              `Combine empirical testing with theoretical modeling to validate both practical and conceptual aspects`,
              `Use only theoretical analysis without empirical validation`,
              `Rely solely on expert opinions and consensus`,
              `Apply the methodology exactly as described without modification`
            ],
            correctAnswer: 0,
            explanation: `This requires understanding of research methodology and the ability to design validation approaches for theoretical content, as expected for ${examLevel} level.`,
            topic: `${topic} - Research Design`,
            difficulty: 'hard',
            questionType: 'methodology'
          }
        ]
      });
    }

    const prompt = this.getTheoryQuizPrompt(content, subject, topic, examLevel); // Pass examLevel

    try {
      const response = await client!.chat.complete({
        model: 'mistral-large-latest',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.4, // Balanced for creativity while maintaining accuracy
        max_tokens: 6000,
      });

      return response.choices[0]?.message?.content || this.getFallbackQuestions(subject, topic, examLevel); // Pass examLevel
    } catch (error: any) {
      console.error('Error generating theory quiz questions:', error);
      // Wrap and rethrow so UI can show popup
  const errMsg = error?.message ?? String(error);
  const e = new Error(errMsg);
  (e as any).code = error?.code ?? error?.status ?? "GENERATION_FAILED";
  throw e;
    }
  }

  private static getTheoryQuizPrompt(content: string, subject: string, topic: string, examLevel: string): string { // Added examLevel
    const truncatedContent = content.length > 8000 ? content.substring(0, 8000) + '...' : content;

    return `You are an expert examination specialist and cognitive assessment designer with 25+ years of experience creating high-level competitive exam questions for ${subject}. Your expertise lies in crafting questions that test deep understanding, critical thinking, and application skills rather than mere memorization.

MISSION: Create 8-12 sophisticated, medium-to-hard difficulty multiple-choice questions based EXCLUSIVELY on the provided theory content for "${topic}" in ${subject}. These questions MUST be specifically tailored to the **${examLevel}** exam level, reflecting the complexity, style, and depth of questions typically found in that examination.

THEORY CONTENT TO ANALYZE:
${truncatedContent}

CRITICAL QUALITY STANDARDS:

1. **DIFFICULTY LEVEL**: MEDIUM TO HARD ONLY, adjusted for **${examLevel}** exam standards.
   - NO basic recall or definition questions
   - Focus on analysis, synthesis, evaluation, and application
   - Require multi-step reasoning and concept integration
   - Test understanding of relationships, implications, and consequences

2. **COGNITIVE COMPLEXITY REQUIREMENTS**:
   - **Analysis**: Break down complex concepts, identify relationships, compare/contrast elements
   - **Synthesis**: Combine multiple concepts, integrate ideas, create new understanding
   - **Evaluation**: Judge validity, assess effectiveness, critique approaches, predict outcomes
   - **Application**: Apply concepts to new situations, solve complex problems, design solutions

3. **QUESTION SOPHISTICATION**:
   - Each question should require 30-60 seconds of thoughtful consideration for a **${examLevel}** aspirant.
   - Avoid questions answerable through simple keyword matching
   - Create scenarios that test conceptual understanding
   - Include questions that require inference and logical reasoning

4. **CONTENT FIDELITY**:
   - Extract ONLY from the provided theory content
   - Use specific terminology, examples, and concepts from the text
   - Maintain scientific/academic accuracy
   - Reference specific details, relationships, or examples mentioned

5. **DISTRACTOR QUALITY** (Incorrect Options):
   - Create plausible but incorrect options that test common misconceptions for a **${examLevel}** level.
   - Include options that are partially correct but incomplete
   - Design distractors that require careful analysis to eliminate
   - Avoid obviously wrong or nonsensical options

QUESTION TYPES TO PRIORITIZE:

**ANALYSIS QUESTIONS** (30%):
- "Analyze the relationship between X and Y. What is the most significant factor that..."
- "Compare the effectiveness of approaches A and B. Which statement best explains..."
- "Examine the underlying assumptions. Which assumption is most critical for..."

**SYNTHESIS QUESTIONS** (25%):
- "Integrate concepts X, Y, and Z. How would you design a solution that..."
- "Combine the principles discussed. What would be the optimal approach to..."
- "Synthesize the information presented. Which strategy would most effectively..."

**EVALUATION QUESTIONS** (25%):
- "Evaluate the validity of the claim that... Which evidence best supports..."
- "Assess the limitations of the approach described. What is the primary weakness..."
- "Judge the effectiveness of the methodology. Under what conditions would it fail..."

**APPLICATION QUESTIONS** (20%):
- "Apply the principles to a new scenario where... What would be the expected outcome..."
- "Given the constraints described, how would you modify the approach to..."
- "Using the framework presented, solve the following complex problem..."

ADVANCED QUESTION STRUCTURES:

1. **Scenario-Based Questions**: Present a complex situation and ask for analysis/solution
2. **Cause-Effect Questions**: Test understanding of relationships and consequences
3. **Comparative Questions**: Require evaluation of multiple approaches/concepts
4. **Predictive Questions**: Ask students to predict outcomes based on principles
5. **Design Questions**: Require students to create solutions using learned concepts
6. **Troubleshooting Questions**: Present problems and ask for diagnostic analysis

JSON RESPONSE FORMAT:
{
  "questions": [
    {
      "id": "unique_id",
      "question": "Sophisticated question requiring deep analysis of content",
      "options": ["Correct answer demonstrating deep understanding", "Plausible but incorrect option", "Another sophisticated distractor", "Complex but wrong alternative"],
      "correctAnswer": 0,
      "explanation": "Detailed explanation connecting answer to specific content elements and demonstrating why other options are incorrect",
      "topic": "${topic} - Specific Aspect",
      "difficulty": "medium|hard",
      "questionType": "analysis|synthesis|evaluation|application"
    }
  ]
}

QUALITY ASSURANCE CHECKLIST:
✓ Each question tests understanding beyond memorization
✓ Questions require 30+ seconds of thoughtful analysis
✓ All options are plausible and require careful consideration
✓ Explanations connect to specific content elements
✓ Questions progress from medium to hard difficulty
✓ Content fidelity is maintained throughout
✓ Academic language and terminology are used appropriately
✓ Questions would challenge even well-prepared students for the **${examLevel}** exam.

FORBIDDEN ELEMENTS:
✗ Simple definition questions ("What is X?")
✗ Direct fact recall ("According to the text, X equals...")
✗ Obvious or silly distractors
✗ Questions answerable without reading the content
✗ Ambiguous or poorly worded questions
✗ Questions with multiple correct answers
✗ Content not present in the provided material

Generate questions that would make a professor proud - sophisticated, challenging, and truly testing deep understanding of ${topic} in ${subject}, specifically for the **${examLevel}** exam.`;
  }

  private static getFallbackQuestions(subject: string, topic: string, examLevel: string): string { // Added examLevel
    return JSON.stringify({
      questions: [
        {
          id: '1',
          question: `Analyze the fundamental principles underlying ${topic} in ${subject}, relevant for ${examLevel} exam. Which factor most significantly influences the overall theoretical framework?`,
          options: [
            'The interconnected nature of core concepts and their dependencies',
            'The chronological order in which concepts were discovered',
            'The complexity of mathematical representations',
            'The number of practical applications available'
          ],
          correctAnswer: 0,
          explanation: `Understanding the interconnected nature of concepts is crucial for mastering ${topic} in ${subject}, as required for ${examLevel} exam.`,
          topic: `${topic} - Fundamental Analysis`,
          difficulty: 'medium',
          questionType: 'analysis'
        },
        {
          id: '2',
          question: `Evaluate the implications of applying ${topic} principles to solve complex problems, typical for ${examLevel} exam. What would be the most critical consideration?`,
          options: [
            'Understanding the boundary conditions and limitations of the theoretical framework',
            'Memorizing all formulas and definitions perfectly',
            'Following procedures exactly as written',
            'Using the most complex approach available'
          ],
          correctAnswer: 0,
          explanation: `Critical evaluation requires understanding limitations and boundary conditions of theoretical applications, a key skill for ${examLevel} exam.`,
          topic: `${topic} - Critical Evaluation`,
          difficulty: 'hard',
          questionType: 'evaluation'
        }
      ]
    });
  }
}
